WIP - genpkg updated popd and pushd

diff --git a/src/genpkg/genpkg b/src/genpkg/genpkg
--- a/src/genpkg/genpkg
+++ b/src/genpkg/genpkg
@@ -1,24 +1,10 @@
 #!/usr/bin/env bash
 
-if [[ -f "$HOME/.config/opium" ]]
-then
-    # shellcheck source=/dev/null
-    source "$HOME/.config/opium"
-fi
-
-if [[ -f "$HOME/Library/Preferences/opium" ]]
-then
-    # shellcheck source=/dev/null
-    source "HOME/Library/Preferences/opium"
-fi
-
 LIBEXEC="../libexec"
-PREFIX=${PREFIX:="/opt/pkg"}
-
-PATH=$PATH:$LIBEXEC
 
 GENPKG_VERSION="0.0.1"
 GENPKG_COMMAND_PATH="$LIBEXEC/genpkg/command"
+GENPKG_FUNCTION_PATH="$LIBEXEC/genpkg/function"
 GENPKG_COMMANDS=()
 GENPKG_DEBUG="false"
 GENPKG_DIR="."
@@ -28,36 +14,33 @@ log() {
 }
 
 error() {
-    >&2 echo "$(tput setaf 1)!> $(tput sgr0)$1"
+    echo "$(tput setaf 1)!> $(tput sgr0)$1"
 }
 
 debug() {
     if [[ "$GENPKG_DEBUG" == true ]]
     then
-        >&2 echo "$(tput setaf 3)#> $(tput sgr0)$1"
+        echo "$(tput setaf 3)#> $(tput sgr0)$1"
     fi
 }
 
-# shellcheck disable=2120
-pushd() {
-    command pushd "$@" > /dev/null || die "genpkg: $GENPKG_DIR: No such directory"
-    debug "Changing directory to $GENPKG_DIR"
+push_d() {
+    local folder
+    folder="$1"
+    pushd "$folder" > /dev/null || die "genpkg: $folder: No such directory"
+    debug "Changing directory to $folder"
 }
 
-# shellcheck disable=2120
-popd() {
+pop_d() {
     local old_dir
-    old_dir=$(dirs -p | sort -r | head -n 1)
-    command popd "$@" > /dev/null || error "genpkg: can't go back to $old_dir"
+    local size
+    size=$(dirs -p | wc -l)
+    old_dir=$(dirs -p | tail -n $((size -1)) | head -n 1)
+    popd > /dev/null || die "genpkg: can't go back to $old_dir"
     debug "Changing directory back to $old_dir"
 }
 
 die() {
-    if [[ "$GENPKG_DIR" != "." ]]
-    then
-        # shellcheck disable=2164
-        popd
-    fi
     error "$1"
     exit "${2:-1}"
 }
@@ -91,6 +74,13 @@ are_commands_loaded() {
     else
         return 0
     fi
+}
+
+load_functions() {
+    while IFS='' read -r line
+    do
+        try_source "$line"
+    done < <(ls $GENPKG_FUNCTION_PATH/*.fct)
 }
 
 load_commands() {
@@ -205,6 +195,7 @@ main() {
         usage
         return 0
     fi
+    load_functions
     load_commands
     debug "Pkgfile: $PKGFILE"
     debug "Directory: $GENPKG_DIR"
@@ -217,15 +208,13 @@ main() {
         shift
         if [[ "$GENPKG_DIR" != "." ]]
         then
-            # shellcheck disable=2164
-            pushd "$GENPKG_DIR"
+            push_d "$GENPKG_DIR"
         fi
         "${_command}_entrypoint" "$@"
         ret="$?"
         if [[ "$GENPKG_DIR" != "." ]]
         then
-            # shellcheck disable=2164
-            popd
+            pop_d
         fi
         return $ret
     fi
